### ISSUE TITLE
[ASScrollNode] Sizing bug

### ISSUE THREAD

**Issue by jennibunny** [facebookarchive/AsyncDisplayKit#2851] opened 2017-01-03 09:26 UTC
Hello,

`ASDisplayNode` is inside `ASScrollNode`.

I want to resize `ASDisplayNode height` based on its subnodes and `ASScrollNode contentSize` based on that `ASDisplayNode`.

**Comment by 8ofproject** [comment] 2017-01-07 20:10
I have the same issue.
Cant find a way to make ASScrollNode's child node bigger then ASScrollNode itself to enable scrolling (all scrolling-bouncing properties set to true).
ASTableNode works, but too complex for the task.
ASDK 2.0.1
Can make example project if necessary.

**Comment by 8ofproject** [comment] 2017-01-07 20:11
The issue looks related to https://github.com/facebook/AsyncDisplayKit/issues/2853

**Comment by 8ofproject** [comment] 2017-01-07 20:56
Example project:
look at _HowJobDoneViewController.swift_
[ScrollExample.zip](https://github.com/facebook/AsyncDisplayKit/files/691700/ScrollExample.zip)

**Comment by hashemp206** [comment] 2017-01-08 11:44
thanks for uploading sample project. I checked, it seem `_contentCalculatedSizeFromLayout` in ASScrollNode that used for `contentSize` of scrollView, has wrong size! but @hannahmbanana needs more investigation.

`ASScrollNode`:
<img width="928" alt="screen shot 2017-01-08 at 2 44 25 pm" src="https://cloud.githubusercontent.com/assets/3206748/21749498/b5c73ac6-d5b4-11e6-8163-b937f02d7ca5.png">.

custom child node of ASScrollNode:
<img width="1099" alt="screen shot 2017-01-08 at 3 13 26 pm" src="https://cloud.githubusercontent.com/assets/3206748/21749520/29f85826-d5b5-11e6-9f29-2466252dcf25.png">

**Comment by hannahmbanana** [comment] 2017-01-10 22:45
@jennibunny @hashemp206 @8ofproject - does this commit address your bug?
e264d94

**Comment by hashemp206** [comment] 2017-01-11 10:18
@hannahmbanana thanks, commit doesn't fixed the issue. here is the sample project: https://github.com/hashemp206/ASScrollNode-Example

**Comment by 8ofproject** [comment] 2017-01-12 22:01
@hannahmbanana I can confirm that nothing has changed (unfortunately).

**Comment by davertay** [comment] 2017-01-30 23:43
+1 for same issue. Example project that one would expect to calculate the correct contentSize height but doesn't: https://github.com/davertay/asdkScrollExample

**Comment by garrettmoon** [comment] 2017-05-01 22:30
Going to close this out since it's community debugging and hasn't been commented on in a while.

**Closed by garrettmoon** 2017-05-01 22:30 UTC
Labels: Community Debugging
