### ISSUE TITLE
Why the text of the ASTextNode is small and the line spacing is less than normal?

### ISSUE THREAD

**Issue by abellee** [facebookarchive/AsyncDisplayKit#3173] opened 2017-03-12 17:50 UTC
this is one example of the AsyncDisplayKit, the font size is modified by me to 12.0
![image](https://cloud.githubusercontent.com/assets/707615/23834299/288c4612-078f-11e7-8b78-e7dec2bb2752.png)

and this is my test project, and definitely clean, the font size is also 12.0
![image](https://cloud.githubusercontent.com/assets/707615/23834306/538c295e-078f-11e7-9400-c301e6a377f6.png)

what settings do I missing?

I don't know why the images show the font size is so close, but in my simulator is totally different, 

but you guys can see the line space, is definitely different,

in my testing project, the line space is so small,

i have the same styles between the example and my testing project.

**Comment by maicki** [comment] 2017-04-25 16:20
Hey @abellee Could you please provide the text example so we can reproduce and may help you with that. Thanks!

**Comment by garrettmoon** [comment] 2017-05-01 23:49
Closing this out since there hasn't been a reply.

**Closed by garrettmoon** 2017-05-01 23:49 UTC
