### ISSUE TITLE
[Question] Excessive memory usage issue (image downloader needs to provide compressed images?)

### ISSUE THREAD

**Issue by ilitvinenko90** [facebookarchive/AsyncDisplayKit#1172] opened 2016-02-03 09:15 UTC
I'm using ASCollectionView with two columns. Each ASCellNode have a lot of content but work well and smoothly.
Now I stuck with issue and don't know how to fix it. 

When I'm scrolling deep down (200-300 CellNode) everything begin to lag. Nodes are not released (method dealloc not called). 

For example: reloadData takes 3 second to complete. 

Should I release cell if they are already not on the screen? If yes, how can I do it? 

I work on iPhone 6 and 6S
Used memmory 250 - 300 mb, CPU at scrolling can reach 180-190%.

Hope that you can help me. Thank you in advance.

**Comment by appleguy** [comment] 2016-02-07 07:31
@ilitvinenko90 the framework is not intended to release ASCellNodes.  as you scroll, every node (including the ASCellNode and every subnode) should have both -clearContents and -clearFetchedData call Barnett. After these methods are called, the memory overhead of the node should be on the order of a very small number of kilobytes. It should take thousands of nodes to add up to a few megabytes, nowhere close to tens or hundreds of megabytes.

Can you please provide some additional information?

- what version of the framework are you using?  Git SHA or version number.
- how are you loading images?  Especially if using SDWebImage, it is essential that you set the framework to provide compressed images to AsyncDisplayKit so it can manage their compression and decompression, otherwise you will get very serious memory problems. Using the AsyncDisplayKit memory management techniques should give you far better memory usage and then in a typical URI kid app using a generic image library.
- what other things are you doing in your ASCellNode?  Should any of those things be released in -clearFetchedData?

Please feel free to email me directly at asyncdisplaykit@gmail.com you have updated this task, or especially if you can send me a test project or reproduction case (I will keep the code confidential in case you can only do this by sharing some of your app source code).  Happy to help, this problem should actually be extremely quick to resolve.  Sorry for the trouble.

**Comment by appleguy** [comment] 2016-02-07 07:32
Here is a reference for when using SDWebImage with ASDK, regarding compression - https://github.com/ide/WebASDKImageManager/issues/2

We will add support for a clean, high performance integration with PINRemoteImage and ASDK in the next month, so look for that (might even land within two weeks).  I highly recommend you use that image library once it is available.

**Comment by yxztj** [comment] 2016-05-17 07:50
@appleguy We're now using 1.9.73, testing using the Kittens example. The memory usage on launch is around 35MB, and after scrolling to bottom then top again, the memory rises to 39MB. Tried simulate memory warning on simulator, the memory usage won't drop. We noticed the image node holds a strong reference to the image object, and since the cell node never gets released, the image stays in memory as well.

We also use ASNetworkImageNode in our own app, with much more complexed and richer images in each cell node, so the memory increases really fast on scrolling down(could go up thens or hundreds of MB and then crashes due to OOM).

Is there any best practice we could follow in this situation? Thanks.

**Closed** 2017-05-01 20:08 UTC
Labels: Community Debugging
