### ISSUE TITLE
[Question] How to control display process of ASCollectionNode?

### ISSUE THREAD

**Issue by mosquitodu** [facebookarchive/AsyncDisplayKit#3049] opened 2017-02-19 14:31 UTC
It's my first time use AsyncDisplaykit. it was great.
I have a collectionnode, tow column, and each item maybe different size. I use the MosaicCollectionViewLayout in demo, and when I insert new items. 
- (void)insertItems:(NSArray*)items
{
    if([items count]){
        NSInteger start = [self.items count];
        NSInteger end = [items count] + start;
        NSMutableArray* indexPaths = [NSMutableArray array];
        for(NSInteger idx = start; idx < end; idx++){
            [indexPaths addObject:[NSIndexPath indexPathForItem:idx inSection:0]];
        }
        [self.items addObjectsFromArray:items];
        dispatch_main_async_safe(^{
            [self.collectionNode performBatchAnimated:YES updates:^{
                [self.collectionNode insertItemsAtIndexPaths:indexPaths];
            } completion:nil];
        });
    }
}
I use nodeBlockForItemAtIndexPath to create node.
it will cause fps down to 50 on iphone6. 

and also when I refresh items use code:
[self.collectionNode performBatchAnimated:NO updates:^{
            [self.items removeAllObjects];
            if([delItems count]){
                [self.collectionNode deleteItemsAtIndexPaths:delItems];
            }
            [self.items addObjectsFromArray:items];
            if([addItems count]){
                [self.collectionNode insertItemsAtIndexPaths:addItems];
            }
        } completion:nil]; 

the collectionnode will flash 
can any one tell me how to improve the performance?

**Comment by appleguy** [comment] 2017-02-21 07:46
@mosquitodu I don't think you have a performance problem, just a timing one -- you're seeing the asynchronous first display.  Could you post a screen capture video, taken with QuickTime Player? (It can record from device too) . This way our suggestion can be most applicable since there can be more than one cause.

If you can take a Time Profile of scrolling on the iPhone 6 and then attach a .zip compressed version of it, I can suggest optimizations quite easily too.  Or send it to me on Slack.

Important: it is unsafe to modify the items array on a background thread and then dispatch to main to update the collection.  The modification of the data (e.g. items) MUST occur at the same moment / inside the performBatchUpdates: block itself.  It is possible that this is one of the causes of the flashing issue too.

Lastly, as a debugging step, try adding reloadDataImmediately in your viewWillAppear method, and make sure you've set reasonable backgroundColor values on your cell's subnodes so the placeholder state looks reasonable (e.g. on each ASTextNode).  If you would rather drop frames than see placeholders, you can enable .neverShowPlaceholders on each ASCellNode before you return it from the nodeBlock.  http://asyncdisplaykit.org/docs/synchronous-concurrency.html

**Comment by mosquitodu** [comment] 2017-02-21 13:40
@appleguy thanks very much! 
Because the file is too big to upload, I upload it to dropbox, please refer to :https://www.dropbox.com/s/v0ng2z1b15lrnde/collectionnode.zip?dl=0
In the video
First. you can see, when I pull down to get new data, the collection node will flash the items even the item not change(I just update data, and call reloadDataImmediately)

Second, when I scrolling down, in willBeginBatchFetchWithContext, I load the data from server, and then just call 
[self.items addObjectsFromArray:items];
            [self.collectionNode performBatchAnimated:YES updates:^{
                [self.collectionNode insertItemsAtIndexPaths:indexPaths];
            } completion:nil];
the fps will drop to 50,some times to 45.

I also attach Time Profile for your reference.

**Comment by mosquitodu** [comment] 2017-02-23 03:11
@appleguy

**Comment by mosquitodu** [comment] 2017-02-23 03:13
@appleguy Thanks your information,  I found some heavy task on main thread in our project, I will rewrite this task, and test it again. thank you very much.

**Comment by garrettmoon** [comment] 2017-05-01 23:39
Going to close this out since it looks like the question was answered.

**Closed by garrettmoon** 2017-05-01 23:39 UTC
