### ISSUE TITLE
[ASViewController] variable height ASTableNode

### ISSUE THREAD

**Issue by robmontesinos** [facebookarchive/AsyncDisplayKit#2055] opened 2016-08-11 03:56 UTC
Conceptual question here. I have an ASViewController with an ASTableNode replacing a class in my app that was based on ASTableView. 

Previously I would change the height of the tableView depending on the presence of an ad banner.

I have been unable to figure out how to change these dimensions with ASTAbleNode. Any help would be appreciated. Unable to determine from the sample apps. Thank you!!

**Comment by hannahmbanana** [comment] 2016-08-11 03:59
@robmontesinos: is the ASTableNode your ASViewController's root node?

**Comment by robmontesinos** [comment] 2016-08-11 04:00
@hannahmbanana yes it is!!

**Comment by hannahmbanana** [comment] 2016-08-11 06:48
Not sure where my previous comment went. :) 

The issue is that the ASViewController's _root_ node gets inherits the bounds of the view controller. If you want to change the frame of the `ASTableNode`, you could supply a dummy `ASDisplayNode` to the ASViewController: `initWithNode:[[ASDisplayNode alloc] init]` and then add the `ASTableNode` as a subnode of the view controller. I am not sure if this is the best way for what you are doing or not, but it is one way of doing it.

**Comment by robmontesinos** [comment] 2016-08-11 20:22
@hannahmbanana Thanks so much Hannah - I will try it and let you know how it goes. Very clever. 

The banner is controlled by a different UIViewController which has several pages - the ASViewController is one of the pages where the ASTableNode height needs to be adjustable due to presence of ad banner or if adbanner is not available, if it returns, if the user purchased remove ad banners, etc.

**Comment by robmontesinos** [comment] 2016-08-11 20:37
This code did not work. Any idea of what I'm doing wrong - cellNodes do not appear

```ObjectiveC

- (instancetype)init {
    // set up root node
    ASDisplayNode *rootNode = [[ASDisplayNode alloc] init];
    
    self = [super initWithNode:rootNode];
    
    if (self) {
        _tableNode = [[ASTableNode alloc] initWithStyle:UITableViewStylePlain];
        [rootNode addSubnode:_tableNode];
        
        _tableNode.delegate = self;
        _tableNode.dataSource = self;
    }
    
    return self;
}

```

**Comment by robmontesinos** [comment] 2016-08-11 20:39
This did the trick - I guess I forgot to set tableNode.view frame

```ObjectiveC

- (void)viewDidLayoutSubviews {
    [super viewDidLayoutSubviews];
        
    self.tableNode.view.frame = [self frameForTableView];
}
```

**Comment by hannahmbanana** [comment] 2016-08-15 05:20
@robmontesinos: Sounds like your variable height table works now, so I'm going to close this issue. If I'm mistaken, feel free to re-open the issue. Thanks for contributing to the AsyncDisplayKit community knowledge by asking this question!

**Comment by robmontesinos** [comment] 2016-08-15 19:33
hi @hannahmbanana - it only works correctly after screen is returned. I set a root node and added a tableNode as a subside of the root node as you suggested. I set the tableView frame at various times trying to get it to the correct height (view height - 50 px to account for ad banner) to no avail. If I push another view controller to the screen and then return to the screen in question, the height is correct, i.e. it shrunk by 50 px.

Can you suggest the correct place, i.e. method, to set the tableView height? I spent an entire day on this to no avail. Thank you in advance.

**Comment by hannahmbanana** [comment] 2016-08-15 20:31
@robmontesinos: would it be possible to create a quick sample project showing this?

**Comment by robmontesinos** [comment] 2016-08-15 20:33
Good idea. I can't do it today but tomorrow for sure. Thank you @hannahmbanana !!

**Comment by robmontesinos** [comment] 2016-08-18 00:49
@hannahmbanana  I gave up on trying to resize ASTableNode - setting up a project with all the network calls was just taking too long - I wound up servicing my needs with the use of tableFooterView - much easier to manipulate the height than the node. Sorry guys

**Comment by garrettmoon** [comment] 2017-05-01 22:28
Going to close this out since it's community debugging and hasn't been commented on in a while.

**Closed by garrettmoon** 2017-05-01 22:28 UTC
Labels: Community Debugging
